spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  batch:
    jdbc:
      initialize-schema: always
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: house
    password: house
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
external:
  apartment-api:
    path: http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev
    service-key: jEIrt7Smf5IMFrn65l99DegsRF5rusgCpOpV6yV8DIPezaaV6gblD4m2Ndrlf%2BNqZzsA4SPnQfDOpnmOP6YDFA%3D%3D

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2